include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "packages/**"
    - "**/*.g.dart"
    - "lib/database/schema_versions.dart"
  errors:
    deprecated_member_use: ignore
    invalid_use_of_protected_member: ignore
    invalid_use_of_visible_for_testing_member: ignore
    experimental_member_use: ignore
    must_call_super: ignore
    dead_code: ignore
    file_names: ignore
    library_private_types_in_public_api: ignore
    avoid_unnecessary_containers: ignore
    overridden_fields: ignore
    constant_identifier_names: ignore
    unused_local_variable: ignore
    dead_null_aware_expression: ignore
    empty_catches: ignore
    implementation_imports: ignore
    prefer_typing_uninitialized_variables: ignore
    curly_braces_in_flow_control_structures: ignore
    depend_on_referenced_packages: ignore
    unnecessary_non_null_assertion: ignore
    unnecessary_nullable_for_final_variable_declarations: ignore
    library_prefixes: ignore
    prefer_is_empty: ignore
    unrelated_type_equality_checks: ignore
    unused_field: ignore
    non_constant_identifier_names: ignore
    const_instance_field: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    use_build_context_synchronously: false
    avoid_print: false
    file_names: false
    library_private_types_in_public_api: false
    avoid_unnecessary_containers: false
    overridden_fields: false
    prefer_interpolation_to_compose_strings: false
    prefer_adjacent_string_concatenation: false
    use_super_parameters: false
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: false
    implementation_imports: false
    depend_on_referenced_packages: false
